import streamlit as st
import pandas as pd
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from googleapiclient.discovery import build
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# --- CONFIGURATION (Loaded from Streamlit Secrets) ---
# We use st.secrets for security so your keys aren't exposed in the code
GOOGLE_API_KEY = st.secrets["GOOGLE_API_KEY"]
SEARCH_ENGINE_ID = st.secrets["SEARCH_ENGINE_ID"]
GMAIL_USER = st.secrets["GMAIL_USER"]
GMAIL_APP_PASSWORD = st.secrets["GMAIL_APP_PASSWORD"]
# Google Sheet Credentials should be a JSON object in secrets
SHEET_CREDENTIALS = st.secrets["SHEET_CREDENTIALS"] 

def search_google(query, num_results=10):
    service = build("customsearch", "v1", developerKey=GOOGLE_API_KEY)
    results = []
    try:
        res = service.cse().list(q=query, cx=SEARCH_ENGINE_ID, num=num_results).execute()
        for item in res.get('items', []):
            results.append({
                'Name': item['title'].split("-")[0].strip(), # Basic parsing
                'Link': item['link'],
                'Snippet': item['snippet']
            })
    except Exception as e:
        st.error(f"Google Search Error: {e}")
    return results

def send_summary_email(user_email, df):
    msg = MIMEMultipart()
    msg['Subject'] = f"Candidate Search Results ({len(df)} found)"
    msg['From'] = GMAIL_USER
    msg['To'] = user_email

    # Convert DataFrame to HTML for the email body
    html_table = df.to_html(index=False)
    
    body = f"""
    <h3>Search Complete</h3>
    <p>Here are the candidates we found based on your criteria:</p>
    {html_table}
    <p><i>This search was generated by your recruiting bot.</i></p>
    """
    msg.attach(MIMEText(body, 'html'))

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.send_message(msg)
        return True
    except Exception as e:
        st.error(f"Email Error: {e}")
        return False

# --- THE USER INTERFACE ---
st.title("🕵️ Passive Candidate Hunter")
st.markdown("Enter a job description or keywords to find candidates on LinkedIn.")

# Input Form
with st.form("search_form"):
    job_keywords = st.text_input("Job Keywords (e.g. Python Developer London)", "Python Developer")
    recipient_email = st.text_input("Where should I email the results?", "your_email@example.com")
    submitted = st.form_submit_button("Find Candidates")

if submitted:
    with st.spinner('Searching the web...'):
        # 1. Build X-Ray Query
        xray_query = f'site:linkedin.com/in/ {job_keywords}'
        
        # 2. Run Search
        candidates = search_google(xray_query, num_results=10)
        
        if candidates:
            df = pd.DataFrame(candidates)
            
            # 3. Show results on screen
            st.success(f"Found {len(candidates)} candidates!")
            st.dataframe(df)
            
            # 4. Email Results
            with st.spinner('Sending email report...'):
                if send_summary_email(recipient_email, df):
                    st.success(f"✅ Report sent to {recipient_email}")
                else:
                    st.error("❌ Failed to send email.")
        else:
            st.warning("No candidates found. Try broadening your keywords.")
